name: life_maintenance
description: "A Flutter app for managing life items, reminders, maintenance, and records."
publish_to: 'none'
version: 0.5.25+26

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  drift: 2.34.2
  drift_flutter: 0.3.1
  shared_preferences: ^2.5.5
  sqlite3: 3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.15.1
  drift_dev: 2.34.4
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
